apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "name" . }}-htpasswd
  namespace: {{ .Release.Namespace }}
data:
  htpasswd: |-
{{ toYaml .Values.registry.htpasswd.credentials | indent 4 }}
