{{- if and .Values.storage.persistence.enabled (not .Values.storage.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
  - {{ .Values.storage.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size | quote }}
  {{- if .Values.storage.persistence.storageClass }}
  {{- if (eq "-" .Values.storage.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.storage.persistence.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
