apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      targetPort: 5000
      protocol: TCP
      name: {{ template "fullname" . }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
