image:
  repository: registry
  tag: 2.6.2
  pullPolicy: IfNotPresent
replicaCount: 1
httpSecret: "ZNRWYiSshmNfBYjsTitGfb6PifR6"
htpasswd:
  enabled: false
  realm: Registry Realm
  credentials: {}
ingress:
  enabled: false
  tls:
    enabled: false
  domain: my.website.com
  annotations: {}
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: "nginx"
service:
  port: 5000
storage:
  delete:
    enabled: false
  s3:
    enabled: false
    accessKey: ""
    secretKey: ""
    region: "us-east-1"
    bucket: ""
    encrypt: true
    secure: true
    v4Auth: true
    chunkSize: 5242880
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi

    # If defined, PVC must be created manually before volume will be bound
    # existingClaim: ""

    # If set to "-", storageClassName: "", which disables dynamic provisioning
    # If undefined or set to null, defaults to the default storageClass
    # storageClass: ""
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 200Mi
  # requests:
  #   cpu: 100m
  #   memory: 200Mi
