image:
  repository: registry
  tag: 2.6.2
  pullPolicy: IfNotPresent
replicaCount: 1
httpSecret: "ZNRWYiSshmNfBYjsTitGfb6PifR6"
htpasswd:
  enabled: false
  realm: Registry Realm
  credentials: {}
ingress:
  enabled: false
  tls:
    enabled: false
  domain: my.website.com
  annotations: {}
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: "nginx"
service:
  port: 5000
storage:
  enabled: false
  delete:
    enabled: false
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 200Mi
  # requests:
  #   cpu: 100m
  #   memory: 200Mi
storage:
  containerPath: /var/lib/registry
  delete:
    enabled: true
