image:
  repository: jetstack/kube-lego
  tag: 0.1.4
  pullPolicy: IfNotPresent
nodeSelector: {}
podAnnotations: {}
replicaCount: 1
resources:
  limits:
    cpu: 20m
    memory: 8Mi
  requests:
    cpu: 20m
    memory: 8Mi
rbac:
  create: false
  serviceAccountName: default
config:
  # Link to environment variables used by kube-lego:
  # https://github.com/jetstack/kube-lego#environment-variables
  LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
  LEGO_PORT: 8080
  LEGO_EMAIL: email@domain.com
