image:
  repository: jetstack/kube-lego
  tag: 0.1.4
  pullPolicy: IfNotPresent
nodeSelector: {}
podAnnotations: {}
replicaCount: 1
resources:
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 200m
    memory: 64Mi
config:
  # Link to environment variables used by kube-lego:
  # https://github.com/jetstack/kube-lego#environment-variables
  LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
  LEGO_PORT: 8080
  LEGO_EMAIL: email@domain.com
  LEGO_CHECK_INTERVAL: 8h
  LEGO_MINIMUM_VALIDITY: 720h # 30 days

