workspace:
  base: /helm-charts
  path: build

pipeline:
  lint-helm-charts:
    image: lachlanevenson/k8s-helm:latest
    commands:
    - helm version -c
    - helm lint --strict ./*

  build-packages:
    image: lachlanevenson/k8s-helm:latest
    commands:
    - helm version -c
    - apk add --update curl
    - sh /helm-charts/build/build-packages.sh

  upload-charts-to-s3:
    image: plugins/s3
    bucket: helm.carldanley.com
    region: us-east-1
    source: /helm-charts/build/charts/**/*
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
