name: nginx-ingress
version: 1.0.3
description: An nginx Ingress controller that uses ConfigMap to store the nginx configuration.
keywords:
- ingress
- nginx
sources:
- https://github.com/carldanley/helm-charts/nginx-ingress
- https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx
maintainers:
- name: carldanley
  email: carldanley@gmail.com
engine: gotpl
