apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "name" . }}-irc
spec:
  ports:
  - port: {{ .Values.service.irc.port }}
    targetPort: 6697
    nodePort: {{ .Values.service.irc.port }}
    protocol: TCP
    name: irc
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
  type: NodePort
