apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "name" . }}-web
spec:
  ports:
  - port: {{ .Values.service.web.port }}
    targetPort: 6698
    protocol: TCP
    name: web
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
