docker:
  apiVersion: "1.23"
server:
  count: 3
  image:
    repository: drone/drone
    tag: 0.8.1
    pullPolicy: IfNotPresent
  isOpen: false
  debug:
    enabled: true
  adminList: {}
  # - UserA
  # - UserB
  organizations: {}
  # - OrganizationA
  # - OrganizationB
  remote:
    type: github
    client: client
    secret: secret
    # url: http://url.com
  resources: {}
  # limits:
  #   cpu: 10m
  #   memory: 20Mi
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
agent:
  count: 3
  image:
    repository: drone/agent
    tag: 0.8.1
    pullPolicy: IfNotPresent
  secret: super-safe-secret
  debug:
    enabled: true
  resources: {}
  # limits:
  #   cpu: 10m
  #   memory: 20Mi
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
  dockerInDocker:
    resources: {}
    # limits:
    #   cpu: 10m
    #   memory: 20Mi
    # requests:
    #   cpu: 10m
    #   memory: 20Mi
ingress:
  enabled: false
  domain: ci.website.com
  tls:
    enabled: false
  annotations: {}
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: "nginx"
service:
  port: 80
database:
  driver: mysql
  datasource: user:pass@tcp(url:3306)/table?parseTime=true
