image:
  repository: drone/drone
  tag: 0.8.1
  pullPolicy: IfNotPresent
docker:
  apiVersion: "1.23"
server:
  isOpen: false
  debug:
    enabled: true
  adminList: {}
  # - UserA
  # - UserB
  organizations: {}
  # - OrganizationA
  # - OrganizationB
  remote:
    type: github
    client: client
    secret: secret
    url: http://url.com
  resources: {}
  # limits:
  #   cpu: 10m
  #   memory: 20Mi
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
agent:
  count: 3
  secret: super-safe-secret
  debug:
    enabled: true
  resources: {}
  # limits:
  #   cpu: 10m
  #   memory: 20Mi
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
ingress:
  enabled: false
  domain: ci.website.com
  annotations: {}
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: "nginx"
service:
  port: 80
database:
  driver: mysql
  datasource: user:pass@tcp(url:3306)/table?parseTime=true
# database dependency settings below
mariadb:
  database:
    name: drone
    root:
      password: root
    user:
      enabled: false
      username: username
      password: password
  persistence:
    enabled: false
    storageClass: "gp2"
    accessMode: ReadWriteOnce
    size: 8Gi
  metrics:
    enabled: true
    image:
      repository: prom/mysqld-exporter
      tag: v0.10.0
      pullPolicy: IfNotPresent
    annotations:
      # prometheus.io/scrape: "true"
      # prometheus.io/port: "9104"
