image:
  repository: drone/drone
  tag: 0.8.1
  pullPolicy: IfNotPresent
docker:
  apiVersion: "1.23"
server:
  isOpen: false
  debug:
    enabled: true
  adminList:
  - carldanley
  - foobar
  organizations:
  - FlexShopper
  - The King's Academy
  remote:
    type: github
    client: client
    secret: secret
    url: http://url.com
  resources: {}
  # limits:
  #   cpu: 10m
  #   memory: 20Mi
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
agent:
  count: 3
  secret: super-safe-secret
  debug:
    enabled: true
  resources: {}
  # limits:
  #   cpu: 10m
  #   memory: 20Mi
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
ingress:
  enabled: true
  domain: ci.website.com
  annotations: {}
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: "nginx"
service:
  port: 443
database:
  driver: mysql
  datasource: user:pass@tcp(url:3306)/table?parseTime=true
