apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "name" . }}
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh"]
        args: ["-c", '
        {{- if .Values.exclude }}
          echo "{{ .Values.exclude.images }}" | tr " " "\n" > /etc/docker-gc-exclude &&
          echo "{{ .Values.exclude.containers }}" | tr " " "\n" > /etc/docker-gc-exclude-containers &&
        {{- end }}
          touch {{ .Values.cron.log }} &&
          echo "{{ .Values.cron.schedule }} /docker-gc >> {{ .Values.cron.log }} 2>&1" | crontab - &&
          crond -L {{ .Values.cron.log }} &&
          tail -f {{ .Values.cron.log }}' ]
        env:
        - name: GRACE_PERIOD_SECONDS
          value: "{{ .Values.env.gracePeriodSeconds }}"
        - name: DOCKER_API_VERSION
          value: "{{ .Values.env.dockerAPIVersion }}"
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
