# nameOverride: some-other-name
dataCenter:
  name: "dc1"
encryptGossip: true
image:
  repository: consul
  tag: 1.0.0
  pullPolicy: IfNotPresent
ingress:
  enabled: false
  domain: consul.domain.tld
  service:
    port: 80
  tls:
    enabled: false
  annotations: {}
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: "nginx"
storage:
  size: 5Gi
  # class: "gp2"
replicas: 3
resources: {}
 # requests:
 #   cpu: 100m
 #   memory: 256Mi
 # limits:
 #   cpu: 500m
 #   memory: 512Mi
backup:
  enabled: false
  image:
    repository: myena/consul-backinator
    tag: latest
    pullPolicy: Always
  encryptionKey: "jqna78gqKlSDLEgFT12wCb1Nexl7"
  s3:
    accessKey: ""
    secretKey: ""
    region: "us-east-1"
    bucketName: ""
    path: "/"
