# nameOverride: some-other-name
image:
  repository: consul
  tag: 0.8.3
  pullPolicy: IfNotPresent
api:
  replicas: 3
  dataCenter:
    name: "dc1"
  gossip:
    encrypt: true
  ingress:
    enabled: false
    domain: api.consul.website.com
    tls:
      enabled: false
    annotations: {}
      # kubernetes.io/tls-acme: "true"
      # kubernetes.io/ingress.class: "nginx"
  storage:
    size: 5Gi
    # class: "gp2"
resources: {}
 # requests:
 #   cpu: 100m
 #   memory: 256Mi
 # limits:
 #   cpu: 500m
 #   memory: 512Mi
