replicaCount: 1
image:
  repository: znc
  tag: 1.6.5
  pullPolicy: IfNotPresent
ingress:
  enabled: false
  domain: ci.website.com
  tls:
    enabled: false
  annotations: {}
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: "nginx"
service:
  port: 80
resources: {}
  # limits:
  #   cpu: 10m
  #   memory: 20Mi
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi

  # If defined, PVC must be created manually before volume will be bound
  # existingClaim: ""

  # If set to "-", storageClassName: "", which disables dynamic provisioning
  # If undefined or set to null, defaults to the default storageClass
  # storageClass: ""
