apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  ## ref: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
  gitlab_omnibus_config: |
    # general settings
    external_url ENV['EXTERNAL_URL'];
    root_pass = ENV['GITLAB_ROOT_PASSWORD'];
    gitlab_rails['initial_root_password'] = root_pass unless root_pass.to_s == '';
    manage_accounts['enable'] = true;
    manage_storage_directories['manage_etc'] = false;
    gitlab_shell['auth_file'] = '/gitlab-data/ssh/authorized_keys';
    git_data_dirs({ "default" => { "path" => "/gitlab-data/git-data" } })
    gitlab_rails['shared_path'] = '/gitlab-data/shared';
    gitlab_rails['uploads_directory'] = '/gitlab-data/uploads';
    gitlab_ci['builds_directory'] = '/gitlab-data/builds';
    gitlab_rails['registry_path'] = '/gitlab-registry';

    # node-exporter
    node_exporter['enable'] = true;

    # postgres
    postgresql['enable'] = false;
    gitlab_rails['db_host'] = ENV['DB_HOST'];
    gitlab_rails['db_port'] = ENV['DB_PORT'];
    gitlab_rails['db_password'] = ENV['DB_PASSWORD'];
    gitlab_rails['db_username'] = ENV['DB_USER'];
    gitlab_rails['db_database'] = ENV['DB_DATABASE'];
    postgres_exporter['enable'] = true;
    postgres_exporter['env'] = {
      'DATA_SOURCE_NAME' => "user=#{ENV['DB_USER']} host=#{ENV['DB_HOST']} port=#{ENV['DB_PORT']} dbname=#{ENV['DB_DATABASE']} password=#{ENV['DB_PASSWORD']} sslmode=disable"
    };

    # redis
    redis['enable'] = false;
    gitlab_rails['redis_host'] = ENV['REDIS_HOST'];
    gitlab_rails['redis_port'] = ENV['REDIS_PORT'];
    gitlab_rails['redis_password'] = ENV['REDIS_PASSWORD'];
    redis_exporter['enable'] = true;
    redis_exporter['flags'] = {
      'redis.addr' => "#{ENV['REDIS_HOST']}:#{ENV['REDIS_PORT']}",
      'redis.password' => "#{ENV['REDIS_PASSWORD']}"
    };

    # registry
    {{- if .Values.registry.enabled }}
    gitlab_rails['registry_enabled'] = true;
    {{- else }}
    gitlab_rails['registry_enabled'] = false;
    {{- end }}

    ## Custom Config
{{ .Values.omnibus.configuration | indent 4 }}

    ## Hardcoded Container Ports (Hardcoded in the Deployment)
    gitlab_workhorse['listen_network'] = 'tcp';
    gitlab_workhorse['listen_addr'] = '0.0.0.0:8005';
    registry['registry_http_addr'] = '0.0.0.0:8105';
    mattermost['service_address'] = '0.0.0.0';
    mattermost['service_port'] = '8065';
    prometheus['listen_address'] = '0.0.0.0:9090';
    node_exporter['listen_address'] = '0.0.0.0:9100';
