{{- if .Values.backups.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "name" . }}-backup
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  schedule: {{ .Values.backups.frequency | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl
            image: google/cloud-sdk
            command:
            - /bin/bash
            - -c
            - pod_name=$(kubectl get pods -n {{ .Release.Namespace }} -l app=gitlab-ce -o jsonpath='{.items[*].metadata.name}');
              kubectl get po/$pod_name;
              kubectl exec -n {{ .Release.Namespace }} $pod_name -- {{ .Values.backups.command }}
          restartPolicy: OnFailure
{{- end }}
