apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        # general settings
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ template "name" . }}
              key: gitlab_omnibus_config
        - name: GITLAB_ROOT_PASSWORD
        {{- if default "" .Values.rootPassword }}
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}
              key: gitlab-root-password
        {{ end }}
        - name: EXTERNAL_URL
          value: {{ default "" .Values.externalUrl | quote }}

        # database configuration
        - name: DB_HOST
          value: {{ .Values.postgres.host | quote }}
        - name: DB_PORT
          value: {{ .Values.postgres.port | quote }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}
              key: postgres-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}
              key: postgres-password
        - name: DB_DATABASE
          value: {{ .Values.postgres.database | quote }}

        # redis configuration
        - name: REDIS_HOST
          value: {{ .Values.redis.host | quote }}
        - name: REDIS_PORT
          value: {{ .Values.redis.port | quote }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}
              key: redis-password
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        {{- if and .Values.registry.enabled }}
        - name: registry
          containerPort: 8105
        {{- end }}
        - name: workhorse
          containerPort: 8005
        - name: prometheus
          containerPort: 9090
        - name: node-exporter
          containerPort: 9100
        livenessProbe:
          httpGet:
            path: /help
            port: http
          initialDelaySeconds: 200
          timeoutSeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /help
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: gitlab-etc
          mountPath: /etc/gitlab
        - name: gitlab-data
          mountPath: /gitlab-data
        - name: gitlab-registry
          mountPath: /gitlab-registry
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: gitlab-etc
      {{- if .Values.persistence.etc.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "name" . }}-etc
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitlab-data
      {{- if .Values.persistence.data.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "name" . }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitlab-registry
      {{- if and .Values.registry.enabled .Values.persistence.registry.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "name" . }}-registry
      {{- else }}
        emptyDir: {}
      {{- end }}
