apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if default "" .Values.rootPassword }}
  gitlab-root-password: {{ default "ignore" .Values.rootPassword | b64enc | quote }}
  {{ end }}

  # postgres
  postgres-username: {{ .Values.postgres.username | b64enc | quote }}
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}

  # redis
  redis-password: {{ .Values.redis.password | b64enc | quote }}
