apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: agent
  name: {{ template "name" . }}-agent
spec:
  replicas: {{ .Values.agent.count }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "name" . }}-agent
        image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
        imagePullPolicy: "{{ .Values.agent.image.pullPolicy }}"
        env:
        - name: DOCKER_API_VERSION
          value: {{ .Values.docker.apiVersion | quote }}
        - name: DRONE_DEBUG
          value: {{ .Values.agent.debug.enabled | default false | quote }}
        - name: DRONE_SECRET
          value: {{ .Values.agent.secret | quote }}
        - name: DRONE_SERVER
          value: "{{ template "name" . }}.{{ .Release.Namespace }}:9000"
        - name: DOCKER_HOST
          value: "tcp://localhost:2375"
        resources:
{{ toYaml .Values.agent.resources | indent 10 }}
      - name: {{ template "name" . }}-dind
        image: docker:dind
        env:
        - name: DOCKER_DRIVER
          value: overlay
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
      volumes:
      - name: docker-graph-storage
        emptyDir: {}
