apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "name" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
    protocol: TCP
    name: server
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: grpc
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    component: server
