{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "name" . }}-http"
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: http
    protocol: "TCP"
    port: {{ .Values.ingress.service.port }}
    targetPort: 8500
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
{{- end }}
