apiVersion: v1
kind: Service
metadata:
  name: "{{ template "name" . }}-internal"
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: http
    protocol: "TCP"
    port: 8500
  - name: rpc
    protocol: "TCP"
    port: 8400
  - name: serf-lan-tcp
    protocol: "TCP"
    port: 8301
  - name: serf-lan-udp
    protocol: "UDP"
    port: 8301
  - name: serf-wan-tcp
    protocol: "TCP"
    port: 8302
  - name: serf-wan-udp
    protocol: "UDP"
    port: 8302
  - name: api
    protocol: "TCP"
    port: 8300
  - name: consul-dns-tcp
    protocol: "TCP"
    port: 8600
  - name: consul-dns-udp
    protocol: "UDP"
    port: 8600
  clusterIP: None
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
