# nameOverride: some-other-name
image:
  repository: vault
  tag: 0.8.3
  pullPolicy: IfNotPresent
devMode: true
service:
  port: 8200
  type: ClusterIP
ingress:
  enabled: false
  domain: vault.domain.tld
  tls:
    enabled: false
  annotations: {}
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: "nginx"
resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
config:
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  listener:
    tcp:
      address: '[::]:8200'
      tls_disable: 1
  storage:
    #consul:
    #  address: ""
    #  path: ""
    #
    #etcd:
    #  address: ""
    #  path: "vault/"
    #
    #s3:
    #  bucket: ""
    #  region: ""
    #  access_key: ""
    #  secret_key: ""
    #  endpoint: "" # When not using AWS S3
