apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
