name: factorio
version: 0.15.36
description: A production factorio server to play with friends.
keywords:
- factorio
sources:
- https://github.com/carldanley/helm-charts/factorio
- https://hub.docker.com/r/dtandersen/factorio/
maintainers:
- name: carldanley
  email: carldanley@gmail.com
engine: gotpl
