image:
  repository: bitnami/mariadb
  tag: 10.1.28-r1
  pullPolicy: IfNotPresent
serviceType: ClusterIP
database:
  name: root
  root:
    password: root
  user:
    enabled: false
    username: guest
    password: guest
# config: |-
#   [mysqld]
#   innodb_buffer_pool_size=2G
persistence:
  enabled: false
  storageClass: "gp2"
  accessMode: ReadWriteOnce
  reclaimPolicy: Retain
  size: 8Gi
metrics:
  enabled: false
  image:
    repository: prom/mysqld-exporter
    tag: v0.10.0
    pullPolicy: IfNotPresent
  resources: {}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
resources: {}
  # limits:
  #   cpu: 256Mi
  #   memory: 250m
  # requests:
  #   cpu: 256Mi
  #   memory: 250m
