image: bitnami/mariadb:10.1.26-r2
imagePullPolicy: IfNotPresent
usePassword: true
serviceType: ClusterIP
# mariadbRootPassword:
# mariadbUser:
# mariadbPassword:
# mariadbDatabase:
metrics:
  enabled: false
  image: prom/mysqld-exporter
  imageTag: v0.10.0
  imagePullPolicy: IfNotPresent
  resources: {}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
resources:
  requests:
    memory: 256Mi
    cpu: 250m
