apiVersion: v1
description: A default backend for DNS without an ingress controller.
name: default-backend
version: 1.0.0
keywords:
  - default-backend
sources:
  - https://github.com/carldanley/helm-charts/default-backend
maintainers:
  - name: Carl Danley
    email: carldanley@gmail.com
engine: gotpl
