apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  mariadb-root-password: {{ .Values.database.root.password | b64enc | quote }}
  {{- if .Values.database.user.enabled }}
  mariadb-password: {{ .Values.database.user.password | b64enc | quote }}
  {{- end }}
