apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "name" . }}
spec:
  template:
    metadata:
      annotations:
    {{- if .Values.controller.podAnnotations }}
{{ toYaml .Values.controller.podAnnotations | indent 8}}
    {{- end }}
      labels:
        app: {{ template "name" . }}
        component: "{{ .Values.controller.name }}"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "name" . }}-{{ .Values.controller.name }}
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
        args:
          - /nginx-ingress-controller
        {{- if .Values.controller.defaultBackend.enabled }}
          - --default-backend-service={{ .Values.controller.defaultBackend.service }}
        {{- end }}
        {{- if (contains "0.9" .Values.controller.image.tag) }}
          - --election-id=ingress-controller-leader
        {{- end }}
        {{- if (contains "0.9" .Values.controller.image.tag) }}
          - --ingress-class=nginx
        {{- end }}
        {{- if (contains "0.9" .Values.controller.image.tag) }}
          - --configmap={{ .Release.Namespace }}/{{ template "name" . }}
        {{- else }}
          - --nginx-configmap={{ .Release.Namespace }}/{{ template "name" . }}
        {{- end }}
        {{- range $key, $value := .Values.controller.extraArgs }}
          - --{{ $key }}={{ $value }}
        {{- end }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        resources:
{{ toYaml .Values.controller.resources | indent 10 }}
      serviceAccountName: {{ template "name" . }}
      terminationGracePeriodSeconds: 60
